-- inserts documento_programa.tipo_documento_programa
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (1,'Hoja de vida','Hoja de vida con soportes','HV',true,'1','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (2,'Sabana de notas de pregrado','Sabana de notas de pregrado','SNP',true,'2','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (3,'Acta y/o diploma pregrado','Acta y/o diplooma de pregrado','ADPR',true,'3','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (4,'Tarjeta profesional','Tarjeta profesional','TP',true,'4','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (5,'Libreta militar','Libreta militar','LM',true,'5','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (6,'Solicitud para modalidad de grado','Solicitud para cursar espacios académicos como modalidad de grado','SMG',true,'6','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (7,'Certificado para modalidad de grado','Certificado de pregrado para modalidad de grado','CMG',true,'7','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (8,'Investigaciones y/o publicaciones','Investigaciones y/o publicaciones','IYP',true,'8','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (9,'Carta de dedicación','Carta de dedicación','CDD',true,'9','5','pdf',now(),now());
INSERT INTO documento_programa.tipo_documento_programa(id, nombre, descripcion, codigo_abreviacion, activo, numero_orden, tamano, extension, fecha_modificacion, fecha_creacion) VALUES (10,'Otros soportes','Otros soportes','OS',true,'10','5','pdf',now(),now());